;;Yarn-1: 2-28 purple
;;Yarn-2: 2-28 green
inhook 2
; Tucks
tuck - f4 2
tuck - f3 2
tuck - f2 2
tuck - f1 2
tuck + b1 2
tuck + b2 2
tuck + b3 2
tuck + b4 2
releasehook 2
inhook 1
; Knits
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
releasehook 1
knit - f4 1
knit - f3 1
knit - b2 1
knit - b1 1
knit - b4 2
knit - b3 2
knit - f2 2
knit - f1 2
outhook 1