;!knitout-2
;;Machine: SWG091N2
;;Gauge: 15
;;Position: Right
;;Carriers: 1 2 3 4 5 6 7 8 9 10
inhook 1;Activating carrier 1
tuck - f9 1
tuck - b8 1
tuck - f7 1
tuck - b6 1
tuck - f5 1
tuck - b4 1
tuck - f3 1
tuck - b2 1
tuck - f1 1
tuck - b0 1
tuck + f0 1
tuck + b1 1
tuck + f2 1
tuck + b3 1
tuck + f4 1
tuck + b5 1
tuck + f6 1
tuck + b7 1
tuck + f8 1
tuck + b9 1
releasehook 1
rack -1;Rack to -1 at 1 gauge
rack -0.75;All Needle racking -1.0
knit - f9 1
knit - b9 1
knit - f8 1
knit - b8 1
knit - f7 1
knit - b7 1
knit - f6 1
knit - b6 1
knit - f5 1
knit - b5 1
knit - f4 1
knit - b4 1
knit - f3 1
knit - b3 1
knit - f2 1
knit - b2 1
knit - f1 1
knit - b1 1
knit - f0 1
knit - b0 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit + b0 1
knit + f0 1
knit + b1 1
knit + f1 1
knit + b2 1
knit + f2 1
knit + b3 1
knit + f3 1
knit + b4 1
knit + f4 1
knit + b5 1
knit + f5 1
knit + b6 1
knit + f6 1
knit + b7 1
knit + f7 1
knit + b8 1
knit + f8 1
knit + b9 1
knit + f9 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit - f9 1
knit - b9 1
knit - f8 1
knit - b8 1
knit - f7 1
knit - b7 1
knit - f6 1
knit - b6 1
knit - f5 1
knit - b5 1
knit - f4 1
knit - b4 1
knit - f3 1
knit - b3 1
knit - f2 1
knit - b2 1
knit - f1 1
knit - b1 1
knit - f0 1
knit - b0 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit + b0 1
knit + f0 1
knit + b1 1
knit + f1 1
knit + b2 1
knit + f2 1
knit + b3 1
knit + f3 1
knit + b4 1
knit + f4 1
knit + b5 1
knit + f5 1
knit + b6 1
knit + f6 1
knit + b7 1
knit + f7 1
knit + b8 1
knit + f8 1
knit + b9 1
knit + f9 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit - f9 1
knit - b9 1
knit - f8 1
knit - b8 1
knit - f7 1
knit - b7 1
knit - f6 1
knit - b6 1
knit - f5 1
knit - b5 1
knit - f4 1
knit - b4 1
knit - f3 1
knit - b3 1
knit - f2 1
knit - b2 1
knit - f1 1
knit - b1 1
knit - f0 1
knit - b0 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit + b0 1
knit + f0 1
knit + b1 1
knit + f1 1
knit + b2 1
knit + f2 1
knit + b3 1
knit + f3 1
knit + b4 1
knit + f4 1
knit + b5 1
knit + f5 1
knit + b6 1
knit + f6 1
knit + b7 1
knit + f7 1
knit + b8 1
knit + f8 1
knit + b9 1
knit + f9 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit - f9 1
knit - b9 1
knit - f8 1
knit - b8 1
knit - f7 1
knit - b7 1
knit - f6 1
knit - b6 1
knit - f5 1
knit - b5 1
knit - f4 1
knit - b4 1
knit - f3 1
knit - b3 1
knit - f2 1
knit - b2 1
knit - f1 1
knit - b1 1
knit - f0 1
knit - b0 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit + b0 1
knit + f0 1
knit + b1 1
knit + f1 1
knit + b2 1
knit + f2 1
knit + b3 1
knit + f3 1
knit + b4 1
knit + f4 1
knit + b5 1
knit + f5 1
knit + b6 1
knit + f6 1
knit + b7 1
knit + f7 1
knit + b8 1
knit + f8 1
knit + b9 1
knit + f9 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit - f9 1
knit - b9 1
knit - f8 1
knit - b8 1
knit - f7 1
knit - b7 1
knit - f6 1
knit - b6 1
knit - f5 1
knit - b5 1
knit - f4 1
knit - b4 1
knit - f3 1
knit - b3 1
knit - f2 1
knit - b2 1
knit - f1 1
knit - b1 1
knit - f0 1
knit - b0 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit + b0 1
knit + f0 1
knit + b1 1
knit + f1 1
knit + b2 1
knit + f2 1
knit + b3 1
knit + f3 1
knit + b4 1
knit + f4 1
knit + b5 1
knit + f5 1
knit + b6 1
knit + f6 1
knit + b7 1
knit + f7 1
knit + b8 1
knit + f8 1
knit + b9 1
knit + f9 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit - f9 1
knit - b9 1
knit - f8 1
knit - b8 1
knit - f7 1
knit - b7 1
knit - f6 1
knit - b6 1
knit - f5 1
knit - b5 1
knit - f4 1
knit - b4 1
knit - f3 1
knit - b3 1
knit - f2 1
knit - b2 1
knit - f1 1
knit - b1 1
knit - f0 1
knit - b0 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit + b0 1
knit + f0 1
knit + b1 1
knit + f1 1
knit + b2 1
knit + f2 1
knit + b3 1
knit + f3 1
knit + b4 1
knit + f4 1
knit + b5 1
knit + f5 1
knit + b6 1
knit + f6 1
knit + b7 1
knit + f7 1
knit + b8 1
knit + f8 1
knit + b9 1
knit + f9 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit - f9 1
knit - b9 1
knit - f8 1
knit - b8 1
knit - f7 1
knit - b7 1
knit - f6 1
knit - b6 1
knit - f5 1
knit - b5 1
knit - f4 1
knit - b4 1
knit - f3 1
knit - b3 1
knit - f2 1
knit - b2 1
knit - f1 1
knit - b1 1
knit - f0 1
knit - b0 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit + b0 1
knit + f0 1
knit + b1 1
knit + f1 1
knit + b2 1
knit + f2 1
knit + b3 1
knit + f3 1
knit + b4 1
knit + f4 1
knit + b5 1
knit + f5 1
knit + b6 1
knit + f6 1
knit + b7 1
knit + f7 1
knit + b8 1
knit + f8 1
knit + b9 1
knit + f9 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit - f9 1
knit - b9 1
knit - f8 1
knit - b8 1
knit - f7 1
knit - b7 1
knit - f6 1
knit - b6 1
knit - f5 1
knit - b5 1
knit - f4 1
knit - b4 1
knit - f3 1
knit - b3 1
knit - f2 1
knit - b2 1
knit - f1 1
knit - b1 1
knit - f0 1
knit - b0 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit + b0 1
knit + f0 1
knit + b1 1
knit + f1 1
knit + b2 1
knit + f2 1
knit + b3 1
knit + f3 1
knit + b4 1
knit + f4 1
knit + b5 1
knit + f5 1
knit + b6 1
knit + f6 1
knit + b7 1
knit + f7 1
knit + b8 1
knit + f8 1
knit + b9 1
knit + f9 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit - f9 1
knit - b9 1
knit - f8 1
knit - b8 1
knit - f7 1
knit - b7 1
knit - f6 1
knit - b6 1
knit - f5 1
knit - b5 1
knit - f4 1
knit - b4 1
knit - f3 1
knit - b3 1
knit - f2 1
knit - b2 1
knit - f1 1
knit - b1 1
knit - f0 1
knit - b0 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit + b0 1
knit + f0 1
knit + b1 1
knit + f1 1
knit + b2 1
knit + f2 1
knit + b3 1
knit + f3 1
knit + b4 1
knit + f4 1
knit + b5 1
knit + f5 1
knit + b6 1
knit + f6 1
knit + b7 1
knit + f7 1
knit + b8 1
knit + f8 1
knit + b9 1
knit + f9 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit - f9 1
knit - b9 1
knit - f8 1
knit - b8 1
knit - f7 1
knit - b7 1
knit - f6 1
knit - b6 1
knit - f5 1
knit - b5 1
knit - f4 1
knit - b4 1
knit - f3 1
knit - b3 1
knit - f2 1
knit - b2 1
knit - f1 1
knit - b1 1
knit - f0 1
knit - b0 1
rack -1;Reset rack from all_needle
rack -0.75;All Needle racking -1.0
knit + b0 1
knit + f0 1
knit + b1 1
knit + f1 1
knit + b2 1
knit + f2 1
knit + b3 1
knit + f3 1
knit + b4 1
knit + f4 1
knit + b5 1
knit + f5 1
knit + b6 1
knit + f6 1
knit + b7 1
knit + f7 1
knit + b8 1
knit + f8 1
knit + b9 1
knit + f9 1
rack -1;Reset rack from all_needle
rack 0;Rack to 0.0 at 1 gauge
outhook 1;Outhooking all active carriers
